name: Update AES256 Encrypted Token Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate random token, encrypt with AES-256, and save to JSON
      env:
        AES_KEY: ${{ secrets.AES_KEY }}   # ASCII string, 32 chars (e.g. "12345678901234567890123456789012")
        AES_IV:  ${{ secrets.AES_IV }}    # ASCII string, 16 chars (e.g. "1234567890123456")
      run: |
        # Generate random token
        TOKEN=$(uuidgen)

        # Convert ASCII to hex
        KEY_HEX=$(echo -n "$AES_KEY" | xxd -p)
        IV_HEX=$(echo -n "$AES_IV" | xxd -p)

        # Encrypt using AES-256-CBC, no salt, base64 output
        ENCRYPTED=$(echo -n "$TOKEN" | openssl enc -aes-256-cbc -nosalt -K "$KEY_HEX" -iv "$IV_HEX" -base64)

        # Save to token.json
        echo "{\"token\": \"$ENCRYPTED\"}" > token.json

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add token.json
        git commit -m "Update AES-encrypted token [skip ci]" || echo "Nothing to commit"
        git push
