name: Update AES256 Encrypted Token Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate random token, encrypt with AES-256, and save to JSON
      env:
        AES_KEY: ${{ secrets.AES_KEY }}   # plain UTF-8 string, e.g. 32 ASCII chars
        AES_IV:  ${{ secrets.AES_IV }}    # plain UTF-8 string, 16 ASCII chars
      run: |
        TOKEN=$(uuidgen)

        # Convert UTF-8 strings to hex
        KEY_HEX=$(echo -n "$AES_KEY" | xxd -p)
        IV_HEX=$(echo -n "$AES_IV" | xxd -p)

        ENCRYPTED=$(echo -n "$TOKEN" | openssl enc -aes-256-cbc -nosalt -K "$KEY_HEX" -iv "$IV_HEX" -base64)

        echo "{\"token\": \"$ENCRYPTED\"}" > token.json

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add token.json
        git commit -m "Update AES-encrypted token [skip ci]" || echo "Nothing to commit"
        git push
