- name: Generate random token, encrypt with AES-256, and save to JSON
      env:
        AES_KEY: ${{ secrets.AES_KEY }}
        AES_IV:  ${{ secrets.AES_IV }}
      run: |
        # Generate a random token
        TOKEN=$(uuidgen)

        # Convert key and IV to hex
        KEY_HEX=$(echo -n "$AES_KEY" | xxd -p -c 256)
        IV_HEX=$(echo -n "$AES_IV" | xxd -p -c 256)

        # Encrypt
        ENCRYPTED=$(echo -n "$TOKEN" | openssl enc -aes-256-cbc -K "$KEY_HEX" -iv "$IV_HEX" -base64)

        # Write to JSON
        echo "{\"token\": \"$ENCRYPTED\"}" > token.json
